// @owner publisher | @since 1.1.0 — demo shell is generated from the clean business entry.
const fs=require('node:fs'),path=require('node:path');const web=require('./project.cjs').web;
const assets=JSON.parse(fs.readFileSync(path.join(web,'asset-manifest.json'),'utf8'));
const scripts=assets.scripts.filter(s=>s!=='integration/config.js'&&!s.endsWith('/app.js'));
scripts.splice(1,0,'demo/generated/templates.js');scripts.push('demo/generated/requirements.js','demo/generated/releases.js','demo/js/demo-store.js','demo/js/receipt-samples.js','demo/js/adapter.js','demo/js/requirements-views.js','demo/js/sfr-layer.js','demo/js/tools.js',assets.scripts.at(-1));
const styles=assets.styles.concat(['demo/css/tools.css','demo/css/sfr.css']);
let html=fs.readFileSync(path.join(web,'application.html'),'utf8').replace(/  <script[^]*?<\/head>/,scripts.map(s=>'  <script src="'+s+'" defer></script>').join('\n')+'\n</head>');
html=html.replace('    <header id="header"',fs.readFileSync(path.join(web,'demo/shell/toolbar.html'),'utf8')+'    <header id="header"').replace('</title>',' · 기능개선 시연</title>').replace('</head>',styles.filter(s=>s.startsWith('demo/')).map(s=>'  <link rel="stylesheet" href="'+s+'">').join('\n')+'\n</head>');
fs.writeFileSync(path.join(web,'index.html'),'<!-- GENERATED by tools/build_demo.cjs. Business entry: application.html; tools: demo/shell/toolbar.html -->\n'+html);
fs.writeFileSync(path.join(web,'demo/asset-manifest.json'),JSON.stringify({scripts,styles},null,2)+'\n');
